import { ChainType, ServiceID } from "./types";

export const RPC_URLS: {
  label: string,
  name: string,
  serviceId: ServiceID, 
  type: ChainType
}[] = [
  {label: "Akash", name: "akash", serviceId: "akash", type: "cosmos"},
  {label: "Arbitrum One", name: "arbitrum-one", serviceId: "arb-one", type: "evm"},
  {label: "Arbitrum One Sepolia", name: "arbitrum-sepolia-testnet", serviceId: "arb-sepolia-testnet", type: "evm"},
  {label: "Atom One", name: "atomone", serviceId: "atomone", type: "cosmos"},
  {label: "Avalanche C-Chain", name: "avax", serviceId: "avax", type: "evm"},
  {label: "Avalanche DFK", name: "avax-dfk", serviceId: "avax-dfk", type: "evm"},
  {label: "Base", name: "base", serviceId: "base", type: "evm"},
  {label: "Base Sepolia", name: "base-testnet", serviceId: "base-test", type: "evm"},
  {label: "Berachain", name: "berachain", serviceId: "bera", type: "evm"},
  {label: "Blast", name: "blast", serviceId: "blast", type: "evm"},
  {label: "Boba", name: "boba", serviceId: "boba", type: "evm"},
  {label: "BSC", name: "bsc", serviceId: "bsc", type: "evm"},
  {label: "Celo", name: "celo", serviceId: "celo", type: "evm"},
  {label: "Cheqd", name: "cheqd", serviceId: "cheqd", type: "cosmos"},
  {label: "Chihuahua", name: "chihuahua", serviceId: "chihuahua", type: "cosmos"},
  {label: "Elys", name: "elys", serviceId: "elys-network", type: "cosmos"},
  {label: "Ethereum", name: "eth", serviceId: "eth", type: "evm"},
  {label: "Ethereum Holesky", name: "eth-holesky-testnet", serviceId: "eth_hol_test", type: "evm"},
  {label: "Ethereum Sepolia", name: "eth-sepolia-testnet", serviceId: "eth_sep_test", type: "evm"},
  {label: "Fantom", name: "fantom", serviceId: "fantom", type: "evm"},
  {label: "Fetch", name: "fetch", serviceId: "fetch", type: "cosmos"},
  {label: "Fraxtal", name: "fraxtal", serviceId: "fraxtal", type: "evm"},
  {label: "Fuse", name: "fuse", serviceId: "fuse", type: "evm"},
  {label: "GIWA Sepolia", name: "giwa-sepolia-testnet", serviceId: "giwa-sepolia-testnet", type: "evm"},
  {label: "Gnosis", name: "gnosis", serviceId: "gnosis", type: "evm"},
  {label: "Harmony", name: "harmony", serviceId: "harmony", type: "evm"},
  {label: "Ink", name: "ink", serviceId: "ink", type: "evm"},
  {label: "IoTeX", name: "iotex", serviceId: "iotex", type: "evm"},
  {label: "Jackal Protocol", name: "jackal", serviceId: "jackal", type: "cosmos"},
  {label: "Juno Network", name: "juno", serviceId: "juno", type: "cosmos"},
  {label: "Kaia", name: "kaia", serviceId: "kaia", type: "evm"},
  {label: "Kava", name: "kava", serviceId: "kava", type: "evm"},
  {label: "Linea", name: "linea", serviceId: "linea", type: "evm"},
  {label: "Mantle", name: "mantle", serviceId: "mantle", type: "evm"},
  {label: "Metis", name: "metis", serviceId: "metis", type: "evm"},
  {label: "Moonbeam", name: "moonbeam", serviceId: "moonbeam", type: "evm"},
  {label: "Moonriver", name: "moonriver", serviceId: "moonriver", type: "evm"},
  {label: "Near", name: "near", serviceId: "near", type: "near"},
  {label: "Oasys", name: "oasys", serviceId: "oasys", type: "evm"},
  {label: "opBNB", name: "opbnb", serviceId: "opbnb", type: "evm"},
  {label: "Optimism", name: "optimism", serviceId: "op", type: "evm"},
  {label: "Optimism Sepolia", name: "optimism-sepolia-testnet", serviceId: "op-sepolia-testnet", type: "evm"},
  {label: "Osmosis", name: "osmosis", serviceId: "osmosis", type: "cosmos"},
  {label: "Persistence", name: "persistence", serviceId: "persistence", type: "cosmos"},
  {label: "Pocket", name: "pocket", serviceId: "pocket", type: "cosmos"},
  {label: "Polygon", name: "polygon", serviceId: "poly", type: "evm"},
  {label: "Polygon Amoy", name: "polygon-amoy-testnet", serviceId: "poly-amoy-testnet", type: "evm"},
  {label: "Polygon zkEVM", name: "polygon-zkevm", serviceId: "poly-zkevm", type: "evm"},
  {label: "Radix", name: "radix", serviceId: "radix", type: "radix"},
  {label: "Router Protocol", name: "router", serviceId: "router", type: "cosmos"},
  {label: "Scroll", name: "scroll", serviceId: "scroll", type: "evm"},
  {label: "Seda Protocol", name: "seda", serviceId: "seda", type: "cosmos"},
  {label: "Sei", name: "sei", serviceId: "sei", type: "evm"},
  {label: "Shentu", name: "shentu", serviceId: "shentu", type: "cosmos"},
  {label: "Solana", name: "solana", serviceId: "solana", type: "svm"},
  {label: "Sonic", name: "sonic", serviceId: "sonic", type: "evm"},
  {label: "Stargaze", name: "stargaze", serviceId: "stargaze", type: "cosmos"},
  {label: "Sui", name: "sui", serviceId: "sui", type: "sui"},
  {label: "Taiko", name: "taiko", serviceId: "taiko", type: "evm"},
  {label: "Taiko Hekla", name: "taiko-hekla-testnet", serviceId: "taiko-hekla-testnet", type: "evm"},
  {label: "Tron", name: "tron", serviceId: "tron", type: "evm"},
  {label: "XRPL EVM", name: "xrplevm", serviceId: "xrplevm", type: "evm"},
  {label: "XRPL EVM Testnet", name: "xrplevm-testnet", serviceId: "xrplevm-testnet", type: "evm"},
  {label: "zkLink Nova", name: "zklink-nova", serviceId: "zklink-nova", type: "evm"},
  {label: "zkSync Era", name: "zksync-era", serviceId: "zksync-era", type: "evm"},
]